#!/bin/bash
if test "$1" = "verbose" || test "$1" = "-v"
then
	exec 3>&1
else
	exec 3>/dev/null
fi

for file in inputs/*.json; do
	test -e "$file" || continue
	basename="${file##*/}"

	if diff "expected_outputs/$basename" \
		<(../json_merger -p "$file") \
		>&3 2>&1
	then
		printf "%s passed test\n" "$file"
	else
		>&2 printf "%s failed test\n" "$file"
		exit 1
	fi
done
